#!/bin/bash
set -euxo pipefail

declare -r dmenucmd='rofi -dmenu'

declare gpt_question
gpt_question=$(${dmenucmd} -p 'Ask ChatGPT: ')

declare gpt_response
gpt_response=$(echo "${gpt_question}" | gpt_prompt || { notify-send "No response from ChatGPT!"; exit 1; })

declare -r application_name='ChatGPT'
declare -i -r notification_timeout='0'

notify-send -a "${application_name}" -t "${notification_timeout}" "${gpt_response}"
